name: League
main: com.meloncraft.league.League
version: 1.0
commands:
   #proxspawn:
      #description: Spawns zombies around players.
      #usage: /proximityspawn
      #permission: proximityspawner.use
      #permission-message: You don't have proximityspawner.use
   #team:
      #description: Adds friend to your team.
      #usage: /team
      #permission: proximityspawner.team
      #permission-message: You don't have proximityspawner.team